// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AreaCascader: typeof import('./src/components/AreaCascader/src/AreaCascader.vue')['default']
    CascaderAddressSelector: typeof import('./src/components/CascaderAddressSelector/src/CascaderAddressSelector.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GlobalDialog: typeof import('./src/components/GlobalDialog/GlobalDialog.vue')['default']
    GlobalFooter: typeof import('./src/components/GlobalFooter/GlobalFooter.vue')['default']
    GlobalHeaderNav: typeof import('./src/components/GlobalHeaderNav/GlobalHeaderNav.vue')['default']
    GlobalInputForm: typeof import('./src/components/GlobalInputForm/GlobalInputForm.vue')['default']
    GlobalTable: typeof import('./src/components/GlobalTable/src/GlobalTable.vue')['default']
    HeaderNav: typeof import("./src/components/GlobalHeaderNav/HeaderNav.vue")["default"]
    NButton: typeof import("naive-ui")["NButton"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
