server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '00000000'
    url: jdbc:mysql://localhost:3306/store_api

# mybatis-plus config
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)